<a href="https://colab.research.google.com/github/Hatthore/UNIVERSIDAD-QUIMICA-GCOLAB/blob/General/MATRICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Definir la matriz A
A = np.array([[3, 2, 1],
              [0,  2, -3],
              [4, 3, 1]])

# Función para calcular el cofactor
def cofactor(matrix, i, j):
    # Menor asociado
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    # Cofactor
    return ((-1) ** (i + j)) * np.linalg.det(minor)

# Calcular la matriz de cofactores
cof_matrix = np.zeros_like(A, dtype=float)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        cof_matrix[i, j] = cofactor(A, i, j)

cof_matrix

array([[ 11., -12.,  -8.],
       [  1.,  -1.,  -1.],
       [ -8.,   9.,   6.]])

In [4]:
# Definir las matrices
matrices_inversa = {
    "a": np.array([[1, -3, 2], [2, 5, 0], [0, -1, -2]]),
    "b": np.array([[8, 7, 6], [2, 1, 0], [5, 4, 3]]),
    "c": np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]),
    "d": np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
}

# Calcular determinantes
determinantes_inversa = {key: round(np.linalg.det(matrix), 5) for key, matrix in matrices_inversa.items()}
determinantes_inversa

{'a': -26.0, 'b': 0.0, 'c': 0.0, 'd': 0.0}

In [10]:
# Definimos la matriz A
A = np.array([[1, 0, 0, 1],
              [1, 2, 3, 2],
              [2, 3, 4, 0],
              [1, 2, -1, -2]])

# Función para calcular el cofactor de un elemento en la matriz
def cofactor(matrix, i, j):
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)  # Eliminar fila i y columna j
    return ((-1) ** (i + j)) * round(np.linalg.det(minor))  # Determinante del menor con signo

# Calculamos la matriz de cofactores
cofactors = np.zeros_like(A, dtype=int)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        cofactors[i, j] = cofactor(A, i, j)

# Transponemos la matriz de cofactores para obtener la adjunta
adjoint = cofactors.T
cofactors, adjoint

(array([[-20,   8,   4,  -4],
        [ 11, -14,   5, -11],
        [ -8,   8,  -8,   8],
        [  1, -10,   7,  -1]]),
 array([[-20,  11,  -8,   1],
        [  8, -14,   8, -10],
        [  4,   5,  -8,   7],
        [ -4, -11,   8,  -1]]))

In [9]:
# Definir las matrices
matrices = {
    "a": np.array([[2, 1, 4, -1], [3, -2, 1, 0], [5, 1, -3, 2], [-1, 3, 3, -1]]),
    "b": np.array([[2, 1, 4, -1], [3, -2, 1, 1], [5, 1, -3, 2], [-1, 3, 3,-1]]),
    "c": np.array([[2, 1, 4, -1], [3, -2, 1, 0], [5, 1, -3, 2], [0, 3, 3, -1]]),
    "d": np.array([[2, 1, 4, -1], [3, 2, 1, 0], [5, 1, -3, 2], [-1, 3, 3, -1]]),
}

# Calcular determinantes
determinantes = {key: round(np.linalg.det(matrix), 5) for key, matrix in matrices.items()}
determinantes

{'a': -0.0, 'b': 76.0, 'c': -13.0, 'd': -24.0}